styles/styles.css

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--eds-eder-main--techdivision.hlx.live/
- After: https://feature-edercms-122--eds-eder-main--techdivision.hlx.live/

EDERCMS-122 EDERCMS-121 colors, fonts, sizes

---

styles/styles.css

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--eds-eder-main--techdivision.hlx.live/
- After: https://feature-edercms-122--eds-eder-main--techdivision.hlx.live/

EDERCMS-122 changed/added colors

---

blocks/table/table.css
blocks/table/table.js

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--eds-eder-main--techdivision.hlx.live/elements/tables
- After: https://feature-edercms-131--eds-eder-main--techdivision.hlx.live/elements/tables

EDERCMS-131: Add table block

---

blocks/events-hero/events-hero.css

[EDERCMS-227](https://techdivision.atlassian.net/browse/EDERCMS-227)
Test URLs:
- Before: https://main--eds-eder-main--techdivision.hlx.live/tools/sidekick/blocks/events
- After: https://feature-edercms-227--eds-eder-main--techdivision.hlx.live/tools/sidekick/blocks/events

EDERCMS-227: Lower image brightness

---

blocks/events-hero/events-hero.css

[EDERCMS-227](https://techdivision.atlassian.net/browse/EDERCMS-227)
Test URLs:
- Before: https://main--eds-eder-main--techdivision.hlx.live/
- After: https://edercms-<branch>--eds-eder-main--techdivision.hlx.live/

EDERCMS-227: Change brightnes to 60%

---

scripts/scripts.js

[EDERCMS-214](https://techdivision.atlassian.net/browse/EDERCMS-214)
Test URLs:
- Before: https://main--eds-eder-main--techdivision.hlx.live/
- After: https://feature-edercms-214--eds-eder-main--techdivision.hlx.live/

EDERCMS-214: Fallback to filename

---

tools/importer/import-events.js
tools/importer/import-news.js
tools/importer/import-util.js
tools/importer/import.js

Test URLs:
- After: https://import-additions-13--eds-eder-main--techdivision.aem.live/

Import additions 13

---

.eslintrc.js
.github/workflows/cleanup-on-create.yaml
404.html
README.md
blocks/fragment/fragment.js
package-lock.json
package.json
scripts/aem.js
scripts/delayed.js
scripts/helpers.js
scripts/scripts.js
scripts/vendor/ffetch.js
styles/lazy-styles.css
thirdparty.md
tools/importer/import-events.js
tools/importer/import-news.js
tools/importer/import-util.js

[EDERCMS-5](https://techdivision.atlassian.net/browse/EDERCMS-5)
Test URLs:
- After: https://update-template--eds-eder-main--techdivision.aem.live/

Update to newest template

---

blocks/language/language.css
blocks/language/language.js

[EDERCMS-219](https://techdivision.atlassian.net/browse/EDERCMS-219)
Test URLs:
- After: https://feature-edercms-219--eds-eder-main--techdivision.aem.live/

EDERCMS-219: Fix language block styling

---

blocks/language/language.css
blocks/language/language.js

[EDERCMS-219](https://techdivision.atlassian.net/browse/EDERCMS-219)
Test URLs:
- After: https://feature-edercms-219--eds-eder-main--techdivision.aem.live/

EDERCMS-219: Add mobile language picker

---

helix-query.yaml

Test URLs:
- After: https://content-report-index--eds-eder-main--techdivision.aem.live/

added first version of content-report index

---

blocks/small-print/small-print.css
blocks/small-print/small-print.js
blocks/table/table.css

[EDERCMS-172](https://techdivision.atlassian.net/browse/EDERCMS-172)
Test URLs:
- After: https://edercms-172--eds-eder-main--techdivision.aem.live/tools/sidekick/blocks/small-print

EDERCMS-172 Small print

---

tools/importer/import-header.js
tools/importer/import-util.js
tools/importer/import.js

Test URLs:
- After: https://import-additions-14--eds-eder-main--techdivision.aem.live/

Import additions 14: url-sections with leading or trailing dashes, special cases for eder-stapler and lelycenterinbayern

---

tools/importer/import-util.js
tools/importer/import.js

Test URLs:
- After: https://import-additions-15--eds-eder-main--techdivision.aem.live/

Import additions 15

---

.multisite/feedstar/styles/theme.css

[EDERCMS-#](https://techdivision.atlassian.net/browse/EDERCMS-#)
Test URLs:
- After: https://feature-edercms-225--eds-eder-main--techdivision.aem.live/

EDERCMS-225: Add feedstar corporate design

---

.multisite/eder-kommunal/styles/theme.css

[EDERCMS-237](https://techdivision.atlassian.net/browse/EDERCMS-237)
Test URLs:
- After: https://edercms-237--eds-eder-main--techdivision.aem.live/

EDERCMS-237 Styling eder kommunal

---

blocks/events-hero/events-hero.css

[EDERCMS-243](https://techdivision.atlassian.net/browse/EDERCMS-243)
Test URLs:
- After: https://feature-edercms-243--eds-eder-main--techdivision.aem.live/

EDERCMS-243: Change hero event height

---

blocks/brand-overview/brand-overview.css
blocks/brand-teaser/brand-teaser.css
blocks/cards/cards.js
blocks/contact-banner/contact-banner.css
blocks/filter/filter.js
blocks/header/header.css
blocks/rows/rows.css
scripts/scripts.js
styles/styles.css

[EDERCMS-#](https://techdivision.atlassian.net/browse/EDERCMS-#)
Test URLs:
- After: https://feature-edercms-233--eds-eder-main--techdivision.aem.live/

EDERCMS-233: Small fixes

---

blocks/news/news.css

[EDERCMS-236](https://techdivision.atlassian.net/browse/EDERCMS-236)
Test URLs:
- After: https://feature-edercms-236--eds-eder-main--techdivision.aem.live/

EDERCMS-236 news overview image size

---

.multisite/agratec-salching/styles/theme.css
.multisite/eder-kommunal/styles/theme.css
.multisite/eder-profi/styles/theme.css
.multisite/feedstar/styles/theme.css
blocks/text-box/text-box.css
styles/theme.css

[EDERCMS-174](https://techdivision.atlassian.net/browse/EDERCMS-#)
Test URLs:
- Before: https://main--eds-eder-main--techdivision.aem.live/tools/sidekick/blocks/text-box
- After: https://feature-edercms-174--eds-eder-main--techdivision.aem.live/tools/sidekick/blocks/text-box

EDERCMS-174 added orange text-box

---

blocks/events/events.css

[EDERCMS-236](https://techdivision.atlassian.net/browse/EDERCMS-236)
Test URLs:
- After: https://feature-edercms-236--eds-eder-main--techdivision.aem.live/

EDERCMS-236 events overview image size

---

blocks/header/header.css
blocks/rows/rows.css

[EDERCMS-144](https://techdivision.atlassian.net/browse/EDERCMS-144)
Test URLs:
- After: https://edercms-244--eds-eder-main--techdivision.aem.live/

EDERCMS-244: Fix logo

---

bin/update-partytown
blocks/thirdparty/thirdparty.js
package-lock.json
scripts/load-resource.js
scripts/load-thirdparty-script.js

[EDERCMS-5](https://techdivision.atlassian.net/browse/EDERCMS-5)
Test URLs:
- After: https://edercms-5-gtm--eds-eder-main--techdivision.aem.live/

EDERCMS-5 Fix GTM debugger

---

blocks/columns/columns.css
blocks/hero-video/hero-video.css

[EDERCMS-5](https://techdivision.atlassian.net/browse/EDERCMS-5)
Test URLs:
- After: https://edercms-5-mobile-styling--eds-eder-main--techdivision.aem.live/

EDERCMS-5 mobile styling

---

blocks/cards/cards.css
blocks/filter/filter.css

[EDERCMS-234](https://techdivision.atlassian.net/browse/EDERCMS-234)
Test URLs:
- After: https://feature-edercms-234--eds-eder-main--techdivision.aem.live/

EDERCMS-234 changes for cards with logos and filter

---

blocks/configurator/configurator.css
blocks/configurator/configurator.js
blocks/thirdparty/thirdparty.js

[EDERCMS-235](https://techdivision.atlassian.net/browse/EDERCMS-235)
Test URLs:
- After: https://edercms-235--eds-eder-main--techdivision.aem.live/drafts/sipperts/configurator

EDERCMS-235 Configurator
